# Generated by Django 4.1.7 on 2023-03-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestMeters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_serie', models.BigIntegerField(db_column='N_serie')),
                ('nombre_medidor', models.CharField(db_column='Nombre medidor', max_length=14)),
                ('appeui', models.CharField(db_column='AppEUI', max_length=18)),
                ('deveui', models.CharField(db_column='DevEUI', max_length=16)),
                ('payload', models.BigIntegerField(db_column='Payload')),
                ('payload_decodificado', models.CharField(db_column='Payload decodificado', max_length=32)),
                ('ultima_revision', models.CharField(db_column='Ultima revision', max_length=10)),
            ],
            options={
                'db_table': 'test_meters',
                'managed': False,
            },
        ),
    ]
