# Generated by Django 4.1.7 on 2023-03-03 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testmeters',
            options={},
        ),
    ]
