# Generated by Django 4.1.7 on 2023-03-08 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_datos_medidores_delete_lora'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datos',
            options={},
        ),
    ]
