# Generated by Django 4.1.7 on 2023-03-08 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_datos_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='datos',
            table='dataloradb.datos',
        ),
    ]
