# Generated by Django 4.1.7 on 2023-03-08 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_datos_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='datos',
            table='datos',
        ),
    ]
